export enum CreateAccountErrorType {
  NONE = "NONE",
  ERROR = "ERROR",
  PASSWORD_DONT_MATCH = "PASSWORD_DONT_MATCH",
  USERNAME_EXISTS = "USERNAME_EXISTS",
  BAD_USERNAME = "BAD_USERNAME",
  WEAK_PASSWORD = "WEAK_PASSWORD",
  EMAIL_IN_USE = "EMAIL_IN_USE",
  EMAIL_INVALID = "EMAIL_INVALID",
}
